### ISSUE TITLE
[FEATURE] Choose installation directory

### ISSUE THREAD

**Issue by JoeJoeTV** [DanielOliveiraSouza/LAMW4Windows-installer#1]
Being able to choose where it gets installed would be very good

**Comment by DanielOliveiraSouza** [comment]
Hello,
Thanks for the suggestion, this feature is not yet available due to the tool design (which does not require user interaction)

**Comment by JoeJoeTV** [comment]
It's just that i really want to install it to a second drive(atleast the android sdk folder) because the android images are so large and take up so much space on my main c drive.
Wouldn't it be possible to have a "Select Directory" Stage in the installer?

**Comment by DanielOliveiraSouza** [comment]
Hello
I understand, but not yet possible, LAMW Manager is a native linux tool and the installer just exists to create a compatibility environment, then run the scripts ...
My suggestion is that you change the path of% HOMEPATH% to another drive in the registry editor.

**Comment by DanielOliveiraSouza** [comment]
In LAMW Manager this functionality is quite complex, the feature is under development and will be available in version v0.3.1

**Comment by DanielOliveiraSouza** [comment]
This feature is now available!
