### ISSUE TITLE
Problem: wrong directory

### ISSUE THREAD

**Issue by dkurtev** [DanielOliveiraSouza/LAMW4Windows-installer#12]
Hi,
After a freash install - try to build a demo project.
If chipset is Aarch64 - no problem, but if is ARM7a+Soft or any other ARM - have error - see the printscreen bellow. Could you help, please?
![laz4android](https://user-images.githubusercontent.com/64217958/80368183-fb3f7a00-8894-11ea-8bfd-dc74aa29557a.jpg)

**Comment by DanielOliveiraSouza** [comment]
Please, Close this demo and create a new project lamw and try build,
if don't work, paste a screenshot

**Comment by DanielOliveiraSouza** [comment]
Do you launched LAMW4Windows from Start Menu ?

**Comment by DanielOliveiraSouza** [comment]
Yes, I understand your error
ARMv7+soft is wrong arch, default is ARMV7 Fpv3

**Comment by dkurtev** [comment]
Hi.
I've tried both : starting Lazarus directly and LAW4Windows from Start menu. Tried all ARM chipsets, and different DEMO projects - the result is allways the same. All ppu files are in the expected folders, but raises this error. Also I have my project built on another computer - Lazarus 2.0.8/FPC 3.0.4 . - where have no support of Aarch64. So I started installation on a new PC. Result of built is the same. No success and with a new project. Any suggestions? 

> Yes, I understand your error
> ARMv7+soft is wrong arch, default is ARMV7 Fpv3

How this could help me ?

**Comment by DanielOliveiraSouza** [comment]
![Captura de Tela (9)](https://user-images.githubusercontent.com/15186872/80456801-958ad680-8904-11ea-8d52-8f2babc6ee5e.png)
By default, lamw4windows uses armv7 + fvp3, when creating a new LAMW project this option is checked. (No need to mess around, unless you want to work with AARCH64)
See screenshot

**Comment by DanielOliveiraSouza** [comment]
Projects from another Iazarus, you must modify the version of the arm at:
Menu-> Project Options -> LAMW Android Project Options -> Build
select armv7a + VFPv3
See screenshot
![Captura de Tela (13)](https://user-images.githubusercontent.com/15186872/80457421-a5ef8100-8905-11ea-9003-bcce538dcf82.png)

**Comment by DanielOliveiraSouza** [comment]
Important:
Don't modified this options:
![Captura de Tela (14)](https://user-images.githubusercontent.com/15186872/80457548-e0591e00-8905-11ea-81ce-27576561a06f.png)

**Comment by dkurtev** [comment]
I understand and know how to switch chipset. But ...error still exisists. 
Yes, I saw that default chipset is armv7+fvp3 , tried to create a new project, same result
![newproject](https://user-images.githubusercontent.com/64217958/80458281-372c1b00-8939-11ea-95df-6342eeeed8df.jpg)

**Comment by dkurtev** [comment]
Could you suggest , how to remove completely and to re-install ?

**Comment by DanielOliveiraSouza** [comment]
You probably edited some file or chose wrong options on the first boot

Open Powershell as admin:

cd D: \ lamw_manager
. \ lamw_manager.bat --reset

**Comment by dkurtev** [comment]
After --reset.
Opened Demo project - armv7+fvp3 - build - success
- same demo - build Aarch64 - success
Open any project - armv7+fvp3 - same problem as before

**Comment by DanielOliveiraSouza** [comment]
You can't use ARMv7+soft, isn't supported!
ARMv7a+VFPv3  is the best option !
